// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// genpop_Rcpp
NumericMatrix genpop_Rcpp(RObject object);
RcppExport SEXP _BRKGApp_genpop_Rcpp(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(genpop_Rcpp(object));
    return rcpp_result_gen;
END_RCPP
}
// genmut_Rcpp
NumericMatrix genmut_Rcpp(RObject object);
RcppExport SEXP _BRKGApp_genmut_Rcpp(SEXP objectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< RObject >::type object(objectSEXP);
    rcpp_result_gen = Rcpp::wrap(genmut_Rcpp(object));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_BRKGApp_genpop_Rcpp", (DL_FUNC) &_BRKGApp_genpop_Rcpp, 1},
    {"_BRKGApp_genmut_Rcpp", (DL_FUNC) &_BRKGApp_genmut_Rcpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_BRKGApp(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
