# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Multiplies two doubles
#'
#' @param v1 First value
#' @param v2 Second value
#' @return Product of v1 and v2
#' @noRd
genpop_Rcpp <- function(object) {
    .Call(`_BRKGApp_genpop_Rcpp`, object)
}

#' Multiplies two doubles
#'
#' @param v1 First value
#' @param v2 Second value
#' @return Product of v1 and v2
#' @noRd
genmut_Rcpp <- function(object) {
    .Call(`_BRKGApp_genmut_Rcpp`, object)
}

